### ISSUE TITLE
Ampersands (and presumably < and >) in certain text fields cause Studio to crash

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#10]
In Open Ended Responses and course announcements (under Updates on the Content menu), text containing ampersands crashes Studio. For open responses, "Studio's having trouble saving your work" message appears, component freezes, and refresh leads to blank component. You have to delete and remake the unit.

In other places, such as Problem components, you get a less catastrophic response (see screenshot below) and can edit and fix the component. It would be nice to have this be the response across the board, or to have ampersands and less than / greater than signs supported in text fields without having to do ```&amp;```

![screen shot 2013-08-01 at 2 52 48 pm](https://f.cloud.github.com/assets/5132757/897563/eca42764-faf4-11e2-9e30-3f5002765c85.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
