### ISSUE TITLE
When Release Date is reached, units marked private are visible to students but still private

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#11]
In my opinion, the whole release date and public/private interaction is too complicated, but it would be nice if we could start by making it so students can *never* see private units.

Also, perhaps we could add a button to mark all units in a section public? This would make it clearer that both release date and public-ness are necessary for something to go live without problems.

**Comment by stvstnfrd** [comment]
Closed as deprecated.
