### ISSUE TITLE
After saving a question on medstats final, on reloading the page, bad "you have submitted" message

### ISSUE THREAD

**Issue by jinpa** [Stanford-Online/edx-platform#13]
I'm getting some odd behavior on the draft of the medstats final, which goes live Sunday night at midnight (so this is fairly urgent).  Students are only allowed to submit each question once, but they can "save" a tentative answer and come back later to submit it.  I did that with question 5, but when I returned to the page (with a re-load), here's what I saw (content of question redacted):

![image](https://f.cloud.github.com/assets/1817245/898384/d6c3beb8-fb0e-11e2-901d-bc6623fa8f16.png)

Note the "Your answer has been submitted" message, despite the correct text below "You have used 0 of 1 submissions".  Can we get that to say "saved" in this case, rather than "submitted"?

Otherwise I think we'll have some worried students.

**Comment by stvstnfrd** [comment]
Closed as deprecated.
