### ISSUE TITLE
Users would like a way to manually set colors of section/subsection labels

### ISSUE THREAD

**Issue by jinpa** [Stanford-Online/edx-platform#15]
We've had a number of requests for changes to course structure (e.g. assign due dates at the unit rather than the sub-section level) that we have to tell people to work around by creating sections and subsections at the level of granularity that works for the system, rather than the level of granularity that they'd prefer.

Given that they're having to use section/subsection labels in ways that they dis-prefer, they'd like to be able to manually change the color (on a per-item basis) that these are displayed to the user as, so that they can achieve different types of visual grouping.  E.g. they might display all sub-sections of a particular sort in green, and another type of subsections in blue.  They'd assign these colors on an item-by-item basis.

In particular, we've got a request for this from Dan Schwartz' on-campus fall course.

**Comment by stvstnfrd** [comment]
Closed as deprecated.
