### ISSUE TITLE
"Reset" button not functional for Open Ended Responses

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#17]
The Reset button does not allow a student to resubmit an answer, as I believe it used to do. It changes the question status from (done) to (not started), but a message comes up saying "You have already answered this question" and the text box remains inaccessible. This is coming up on questions that should be allowing up to 10 attempts. Whatever grade the student assigned themselves remains up on the progress page.

See any of the self-assessment questions in How To Learn Math. Below is a screenshot – note the question status at the top and the message at the bottom:
![screen shot 2013-08-06 at 11 59 20 am](https://f.cloud.github.com/assets/5132757/919494/59208562-feca-11e2-9652-a707125b3bad.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
