### ISSUE TITLE
"Tasks Average" on Progress page includes unattempted tasks as 0% grades

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#19]
In the following image, the Tasks Average and Total columns are the same. It seems like we should be calculating the Average for an assignment type based on the subset of questions that the student has attempted, rather than on all of them. Maybe we should add "to date" to the column label? The Total column should remain as it is.

![image](https://f.cloud.github.com/assets/5132757/928422/33e3a800-ffb6-11e2-92f3-4bd888d74510.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
