### ISSUE TITLE
Text for "staff grading" makes it sound like it's all about ML grading

### ISSUE THREAD

**Issue by jinpa** [Stanford-Online/edx-platform#21]
This doesn't make sense for assessments that don't use ML (but still require staff grading for calibration).  See below for current text.

INSTRUCTIONS

This is the list of problems that currently need to be graded in order to train the machine learning models. Each problem needs to be trained separately, and we have indicated the number of student submissions that need to be graded in order for a model to be generated. You can grade more than the minimum required number of submissions--this will improve the accuracy of machine learning, though with diminishing returns. You can see the current accuracy of machine learning while grading.

**Comment by stvstnfrd** [comment]
Closed as deprecated.
