### ISSUE TITLE
Improvement of default component Display Names

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#22]
When you create a component, the default Display Name is not useful. Right now, it says things like "Blank HTML Page" or "Blank Advanced Problem," and these names are visible as tooltips when you hover over them in the course. It is easy to forget to change these, as every single component has one. It would be better if the field was blank by default or if it just said something basic (and not obviously out of place), such as "Problem," "Video," or "Text."

![screen shot 2013-08-14 at 12 26 19 pm](https://f.cloud.github.com/assets/5132757/964514/6e09fef6-0517-11e3-906b-80e4c0f8498e.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
