### ISSUE TITLE
Swap styling and order of Save and Submit buttons

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#23]
Right now, the Save button really jumps out to be clicked on because it is bright blue, in contrast with the plain Submit button. This is counterintuitive, especially since I would guess that most users use Submit more often. This also compounds the issue with the unclear labeling of the buttons (Submit vs. Check vs. Save) by making Save seem like the more important button. Could we have the button on the left be a plain-styled Save and the button on the right be an eye-catching Submit?

![screen shot 2013-08-14 at 4 48 02 pm](https://f.cloud.github.com/assets/5132757/966090/59263d0e-053c-11e3-8251-b5cfd150579e.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
