### ISSUE TITLE
Change styling of "Publish Draft" and "Delete Draft" in Studio

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#24]
When you edit a draft, the system emphasizes the option to delete that draft over the option to publish that draft. This never fails to cause a moment of disorientation for me at least, and it risks causing a user to delete their changes. Could "Publish Draft" be a blue button and "Delete Draft" be a red button next to it?
![screen shot 2013-08-14 at 4 54 13 pm](https://f.cloud.github.com/assets/5132757/966113/1382fa7a-053d-11e3-8af3-874495a8a042.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
