### ISSUE TITLE
Make default location of new Discussion post equal current location in forum

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#25]
Currently, when a user clicks the New Post button in the forums, the default location is whichever category is alphabetically first. In Jo's course, this is External Resources:
![screen shot 2013-08-14 at 5 09 22 pm](https://f.cloud.github.com/assets/5132757/966171/0d1d40ee-053f-11e3-98fb-f27969523967.png)

As you can see below, this has led to users posting irrelevant things to the External Resources:
![screen shot 2013-08-14 at 5 08 58 pm](https://f.cloud.github.com/assets/5132757/966177/28490aba-053f-11e3-826d-8fd7d5a8e390.png)

One solution would be to make the default location be the category the user is already in – if they were browsing Study Groups, that field would default to Study Groups, etc. It would also be nice if the course staff could set a default location for posts in a setting somewhere (e.g. default location is General, so even posts created while viewing the Show All Discussions category have a meaningful place to go)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
