### ISSUE TITLE
Double negative for Open Ended Response quality filter

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#26]
The quality filter option is worded counterintuitively. Here's a screenshot:

![screen shot 2013-08-16 at 4 28 04 pm](https://f.cloud.github.com/assets/5132757/978862/8ffca648-06cb-11e3-8212-2c09642a04a5.png)

Could we make this "Enable quality filter: True" instead?

**Comment by stvstnfrd** [comment]
Closed as deprecated.
