### ISSUE TITLE
Export Open Ended Responses as text document

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#27]
I've heard this as a request from both students and professors. Students would like to be able to export all of their open ended responses as a text file so that they don't have to go through the courseware and copy and paste.

Separately, professors (or at least Jay Pfaffman) would like to be able to see all of the open ended responses for a particular question, and perhaps share them with students.   Could we add a button somewhere – perhaps in the assessment panel? – that would let people do this?

**Comment by stvstnfrd** [comment]
Closed as deprecated.
