### ISSUE TITLE
Export Progress page as "syllabus" 

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#28]
It would be great if a user could export the progress page as a sort of syllabus mockup or basic skeleton frame. It could just list each section, subsection, and activity that has been released so far, and it could have each problem score listed next to the problem's name. Something basic like

![screen shot 2013-08-16 at 4 50 28 pm](https://f.cloud.github.com/assets/5132757/978948/a854e086-06ce-11e3-9c40-e54234d32209.png)

but with better formatting? That would give more information than the progress page does so far, and it would allow users to see more of a big picture look at the course than the Courseware tab does. I've heard from users that they would like to see the overall structure of a course, and I think we need to improve the usability of the Progress page anyway (the long lines of scores without problem names are not very readable).

**Comment by stvstnfrd** [comment]
Closed as deprecated.
