### ISSUE TITLE
Optout in django admin is missing a list_display

### ISSUE THREAD

**Issue by sefk** [Stanford-Online/edx-platform#4]
Optout needs to have an explicit class defined so you can set the list_display attribute.  Without that is just shows as "Optout object", see screenshot:

![screen shot 2013-07-29 at 11 05 56 pm](https://f.cloud.github.com/assets/621565/876831/e607845e-f8de-11e2-96fc-4f025ba48cfa.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
