### ISSUE TITLE
Studio is breaking on origin/master

### ISSUE THREAD

**Issue by azimpradhan** [Stanford-Online/edx-platform#406]
<img width="1201" alt="screen shot 2016-01-19 at 3 04 02 pm" src="https://cloud.githubusercontent.com/assets/1752973/12434813/021e0378-bebe-11e5-9c42-ce68a43af0f4.png">

Studio hits a 404 when trying to load feedback.js
I did a search through our commit history to pinpoint the commit that causes a break and found that the commit is this one:
https://github.com/Stanford-Online/edx-platform/commit/a18aa6336c803a056703b26cf420a4eea6cf349c
(Cohorts visibility fix from upstream #398)
@kluo, could you look into this when you get a chance.

**Comment by stvstnfrd** [comment]
Resolved with #408
