### ISSUE TITLE
Changing name of Open Ended Response component does not change name shown in Peer Grading Interface

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#7]
Once you've saved an Open Ended Response component, going back and editing the Display Name will change the name wherever it appears in Courseware but not in the Assessment Panel or Peer Grading Interface. For example, I changed the name of "Question 6.4" to "Question 6.4 (peer feedback)", but this is not reflected below (ignore the duplicates, that's another bug). Potentially annoying if you don't think to change the display name the first time you edit a component – you end up with a lot of "Open Ended Response" items that are difficult to distinguish between.

![screen shot 2013-07-31 at 2 43 36 pm](https://f.cloud.github.com/assets/5132757/889975/4bf3dfa0-fa2a-11e2-964d-46cd1dd68dcc.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
