### ISSUE TITLE
Tooltips containing component Display Name leave blank space for components with no display name

### ISSUE THREAD

**Issue by nthaniel** [Stanford-Online/edx-platform#9]
When you remove the display name (as I did below with a minor HTML component between the video and discussion), there is a blank space in the tooltip that did not appear before the most recent release.

![screen shot 2013-08-01 at 2 45 03 pm](https://f.cloud.github.com/assets/5132757/897498/d0b1b2b6-faf3-11e2-8469-45f5128ecbb3.png)

**Comment by stvstnfrd** [comment]
Closed as deprecated.
